WITH CTE as (
    SELECT BOOK_ID
    , SUM(SALES) as TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022'
    AND MONTH(SALES_DATE) = '01'
    GROUP BY BOOK_ID
)

SELECT a.AUTHOR_ID
, b.AUTHOR_NAME
, a.CATEGORY
, SUM(a.PRICE * c.TOTAL_SALES) as TOTAL_SALES
FROM BOOK a
JOIN AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
JOIN CTE c on c.BOOK_ID = a.BOOK_ID
GROUP BY a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY
ORDER BY 1 ASC, CATEGORY DESC;