WITH CTE AS (
    SELECT CART_ID,
           MAX(CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END) AS HAS_MILK,
           MAX(CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END) AS HAS_YOGURT
    FROM CART_PRODUCTS
    GROUP BY CART_ID
)
SELECT CART_ID
FROM CTE
WHERE HAS_MILK = 1 AND HAS_YOGURT = 1
ORDER BY CART_ID ASC;
