-- 코드를 입력하세요
(SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE
, PRODUCT_ID
, USER_ID
, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE) = '2022'
AND MONTH(SALES_DATE) = '03'

UNION ALL

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") as SALES_DATE
, PRODUCT_ID
, NULL AS USER_ID
, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE) = '2022'
AND MONTH(SALES_DATE) = '03')

ORDER BY 1 ASC, 2 ASC, 3 ASC