(SELECT a.ANIMAL_ID
, a.ANIMAL_TYPE
, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE NOT LIKE 'Spayed%'
AND b.SEX_UPON_OUTCOME LIKE 'Spayed%'

UNION

SELECT a.ANIMAL_ID
, a.ANIMAL_TYPE
, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE NOT LIKE 'Neutered%'
AND b.SEX_UPON_OUTCOME LIKE 'Neutered%')

ORDER BY ANIMAL_ID ASC