WITH CTE as(
    SELECT USER_ID
    , YEAR(SALES_DATE) as YEAR
    , MONTH(SALES_DATE) as MONTH
    FROM ONLINE_SALE
)

SELECT c.YEAR
, c.MONTH
, a.GENDER
, COUNT(DISTINCT(c.USER_ID)) as USERS
FROM USER_INFO a
JOIN CTE c on a.USER_ID = c.USER_ID
WHERE a.GENDER IS NOT NULL
GROUP BY c.YEAR, c.MONTH, a.GENDER
ORDER BY 1 asc, 2 asc, 3 asc