-- 코드를 입력하세요
WITH CTE AS (SELECT b.ONLINE_SALE_ID
, b.USER_ID
, b.PRODUCT_ID
, b.SALES_AMOUNT
, YEAR(b.SALES_DATE) as YEAR
, MONTH(b.SALES_DATE) as MONTH
FROM USER_INFO a
JOIN ONLINE_SALE b on a.USER_ID = b.USER_ID
WHERE YEAR(a.JOINED) = '2021'),

TOTAL AS (
    SELECT COUNT(USER_ID) AS total_users
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT c.YEAR
, c.MONTH
, COUNT(DISTINCT c.USER_ID) as PURCHASED_USERS
, ROUND(SUM(c.SALES_AMOUNT) / t.total_users, 1) as PUCHASED_RATIO
FROM CTE c
CROSS JOIN TOTAL t
GROUP BY c.YEAR, c.MONTH
ORDER BY c.YEAR ASC, c.MONTH ASC;