WITH RECURSIVE GENERATION AS (
  -- 1세대: 부모가 없는 대장균
  SELECT ID, PARENT_ID, 1 AS GENERATION
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL

  UNION ALL

  -- 재귀: 부모가 이전 세대의 ID인 경우 세대 + 1
  SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
  FROM ECOLI_DATA e
  JOIN GENERATION g
    ON e.PARENT_ID = g.ID
),
-- 자식이 없는 개체만 추출
GEN_NO_CHILDREN AS (
  SELECT g.ID, g.GENERATION
  FROM GENERATION g
  LEFT JOIN ECOLI_DATA e
    ON g.ID = e.PARENT_ID
  WHERE e.ID IS NULL
)
-- 세대별로 묶어서 개수 세기
SELECT COUNT(ID) AS COUNT, GENERATION
FROM GEN_NO_CHILDREN
GROUP BY GENERATION
ORDER BY GENERATION;
