-- 코드를 입력하세요
SELECT a.PRODUCT_ID
, a.PRODUCT_NAME
, SUM(a.PRICE * b.amount) as TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b on a.PRODUCT_ID = b.PRODUCT_ID
WHERE YEAR(b.PRODUCE_DATE) = '2022'
AND MONTH(b.PRODUCE_DATE) = '05'
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;