WITH half as(
    SELECT SHIPMENT_ID
    , FLAVOR
    , SUM(TOTAL_ORDER) as TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
),

july as(
    SELECT SHIPMENT_ID
    , FLAVOR
    , SUM(TOTAL_ORDER) as TOTAL
    FROM JULY
    GROUP BY FLAVOR
)

SELECT a.FLAVOR
FROM half a
JOIN july b on a.FLAVOR = b.FLAVOR
GROUP BY a.FLAVOR
ORDER BY SUM(a.TOTAL + b.TOTAL) DESC
LIMIT 3;