-- 코드를 입력하세요
SELECT b.APNT_NO
, a.PT_NAME
, a.PT_NO
, b.MCDP_CD
, c.DR_NAME
, b.APNT_YMD
FROM PATIENT a
JOIN APPOINTMENT b on a.PT_NO = b.PT_NO
JOIN DOCTOR c on c.DR_ID = b.MDDR_ID
WHERE DATE(b.APNT_YMD) = '2022-04-13%'
AND b.APNT_CNCL_YN = 'N'
AND c.MCDP_CD = 'CS'
ORDER BY b.APNT_YMD ASC