WITH RECURSIVE hours AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM hours WHERE h < 23
)
SELECT h AS HOUR, IFNULL(COUNT(입양.ANIMAL_ID), 0) AS COUNT
FROM hours
LEFT JOIN ANIMAL_OUTS AS 입양
  ON h = HOUR(입양.DATETIME)
GROUP BY h
ORDER BY h;
