-- 코드를 입력하세요
SELECT a.WRITER_ID as USER_ID
, b.NICKNAME
, SUM(a.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD a
JOIN USED_GOODS_USER b on a.WRITER_ID = b.USER_ID
WHERE a.STATUS = 'DONE'
GROUP BY USER_ID, NICKNAME
HAVING SUM(a.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;