SELECT b.ID
, b.GENOTYPE , a.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA AS a   -- 부모
JOIN ECOLI_DATA AS b   -- 자식
  ON a.ID = b.PARENT_ID
WHERE (a.GENOTYPE & b.GENOTYPE) = a.GENOTYPE
ORDER BY b.ID ASC;