-- 코드를 입력하세요
SELECT DISTINCT(a.CAR_ID) as CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
JOIN CAR_RENTAL_COMPANY_CAR b on a.CAR_ID = b.CAR_ID
WHERE b.CAR_TYPE = '세단'
AND MONTH(a.START_DATE) = '10'
ORDER BY CAR_ID DESC;