WITH CTE as (SELECT a.ID
, b.FISH_NAME
, a.LENGTH
, MAX(a.LENGTH) OVER (PARTITION BY a.FISH_TYPE) as MAX_LEN
FROM FISH_INFO a
JOIN FISH_NAME_INFO b on a.FISH_TYPE = b.FISH_TYPE
ORDER BY ID ASC)

SELECT ID, FISH_NAME, MAX_LEN as LENGTH
FROM CTE
WHERE LENGTH = MAX_LEN
ORDER BY ID ASC