WITH avg_sal as (
SELECT DEPT_ID, ROUND(AVG(SAL)) as AVG_SAL FROM HR_EMPLOYEES GROUP BY DEPT_ID
)
SELECT a.DEPT_ID, a.DEPT_NAME_EN, b.AVG_SAL
FROM HR_DEPARTMENT a
JOIN avg_sal b on a.DEPT_ID = b.DEPT_ID
ORDER BY b.AVG_SAL DESC;