-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', b.BOARD_ID, '/', b.FILE_ID, b.FILE_NAME, b.FILE_EXT) as FILE_PATH
FROM (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) a
LEFT JOIN USED_GOODS_FILE b on a.BOARD_ID = b.BOARD_ID
ORDER BY FILE_PATH DESC