-- 코드를 입력하세요
WITH total as (
SELECT BOOK_ID, SUM(SALES) as TOTAL_SALES
    FROM BOOK_SALES
    WHERE YEAR(SALES_DATE) = '2022'
    AND MONTH(SALES_DATE) = '01'
    GROUP BY BOOK_ID
)

SELECT a.CATEGORY
, SUM(b.TOTAL_SALES) as TOTAL_SALES
FROM BOOK a
JOIN total b on a.BOOK_ID = b.BOOK_ID
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY