-- 코드를 입력하세요
WITH CTE as (SELECT CATEGORY
, PRODUCT_NAME
, PRICE
, MAX(PRICE) OVER (PARTITION BY CATEGORY) as MAX_PRICE
FROM FOOD_PRODUCT)

SELECT CATEGORY
, MAX_PRICE
, PRODUCT_NAME
FROM CTE
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND PRICE =  MAX_PRICE
ORDER BY MAX_PRICE DESC;
