WITH A_g as (
    SELECT SUM(CODE) as GRADE_SUM
FROM SKILLCODES
WHERE CATEGORY = "Front End" or NAME = "Python"
),

B_g as (
    SELECT SUM(CODE) as GRADE_SUM
    FROM SKILLCODES
    WHERE NAME = "C#"
),

C_g as (
    SELECT SUM(CODE) as GRADE_SUM
FROM SKILLCODES
    WHERE NAME != "C#" and NAME != "Python" and CATEGORY = "Front End"
)

(SELECT "A" as GRADE
, a.ID
, a.EMAIL
FROM DEVELOPERS a
JOIN A_g aa on a.SKILL_CODE & aa.GRADE_SUM > 0

UNION

SELECT "B" as GRADE
, b.ID
, b.EMAIL
FROM DEVELOPERS b
JOIN B_g bb on b.SKILL_CODE & bb.GRADE_SUM > 0

UNION

SELECT "C" as GRADE
, c.ID
, c.EMAIL
FROM DEVELOPERS c
JOIN C_g cc on c.SKILL_CODE & cc.GRADE_SUM > 0)

ORDER BY GRADE, ID

